M48
; DRILL file {KiCad (6.0.7)} date Mon Apr 17 23:48:33 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-17T23:48:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X6.1476Y-4.0551
X6.1476Y-4.2126
T2
X4.2028Y-3.5827
X4.2028Y-4.685
X6.0335Y-3.5827
T3
X4.0256Y-4.1339
T0
M30
