M48
; DRILL file {KiCad (6.0.7)} date Mon Apr  3 16:37:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-03T16:37:45-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X6.1102Y-4.0354
X6.1102Y-4.2323
T2
X4.0256Y-4.1339
T0
M30
